'use client'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { csrfFetch } from '@/lib/csrf'
import { COUNTRIES } from '@/lib/countries'
import { AlertBanner } from '@/components/ui/alert-banner'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

export function CompleteGoogleProfile({ identity }: { identity: { email: string; firstName: string; lastName: string } }) {
  const router = useRouter(); const [role, setRole] = useState<'STUDENT' | 'SUPERVISOR'>('STUDENT'); const [universities, setUniversities] = useState<{ id: string; name: string }[]>([]); const [universityId, setUniversityId] = useState(''); const [universityName, setUniversityName] = useState(''); const [country, setCountry] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  useEffect(() => { void csrfFetch('/api/universities').then((response) => response.json()).then((data) => setUniversities(data.universities ?? [])).catch(() => setUniversities([])) }, [])
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const other = universityId === 'other'; const response = await csrfFetch('/api/auth/google/complete-profile', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ role, universitySelectionMode: other ? 'OTHER' : 'EXISTING', ...(other ? { universityName, country } : { universityId, country }) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); router.push('/dashboard'); router.refresh() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Registration failed') } finally { setLoading(false) } }
  return <form onSubmit={submit} className="space-y-5">{error && <AlertBanner variant="error">{error}</AlertBanner>}<div className="grid gap-4 sm:grid-cols-2"><div><Label>First name</Label><Input value={identity.firstName} readOnly/></div><div><Label>Last name</Label><Input value={identity.lastName} readOnly/></div></div><div><Label>Email</Label><Input value={identity.email} readOnly/></div><div><Label htmlFor="google-university">University</Label><select id="google-university" className="flex h-11 w-full rounded-md border border-input bg-card px-3.5 text-foreground" value={universityId} onChange={(event) => setUniversityId(event.target.value)} required><option value="">Select your university</option>{universities.map((university) => <option key={university.id} value={university.id}>{university.name}</option>)}<option value="other">Other</option></select></div>{universityId === 'other' && <div><Label htmlFor="google-university-name">University name</Label><Input id="google-university-name" value={universityName} onChange={(event) => setUniversityName(event.target.value)} required/></div>}<div><Label htmlFor="google-country">Country</Label><select id="google-country" className="flex h-11 w-full rounded-md border border-input bg-card px-3.5 text-foreground" value={country} onChange={(event) => setCountry(event.target.value)} required><option value="">Select country</option>{COUNTRIES.map((item) => <option key={item}>{item}</option>)}</select></div><div><Label>I am a</Label><div className="grid grid-cols-2 gap-3">{(['STUDENT', 'SUPERVISOR'] as const).map((item) => <Button key={item} type="button" variant={role === item ? 'default' : 'outline'} onClick={() => setRole(item)}>{item === 'STUDENT' ? 'Student' : 'Supervisor'}</Button>)}</div></div><Button className="w-full" disabled={loading}>{loading ? 'Creating account…' : 'Complete registration'}</Button></form>
}
