'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import { AlertCircle, CheckCircle2, Download, FileSpreadsheet, Loader2, Pencil, RotateCcw, Sparkles, UploadCloud, Users, XCircle } from 'lucide-react'
import { toast } from 'sonner'
import { previewSupervisorRoster, confirmSupervisorRoster, getSupervisorRosterHistory, recordImportAssistOutcome, requestImportLayoutAssist, requestImportRepairAssist } from '@/features/teams/roster-import-api'
import type { ImportAssistSuggestion, TeamImportColumnMapping, TeamImportConfirmResult, TeamImportMetadata, TeamImportOverride, TeamImportPreviewRow, TeamImportPreviewSummary } from '@/lib/team-import/types'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { AlertBanner } from '@/components/ui/alert-banner'
import { ConfirmDialog } from '@/components/ui/confirm-dialog'
import { Input } from '@/components/ui/input'

type Preview = { batchId: string; fileHash: string; fileName: string; metadata: TeamImportMetadata; fileWarnings: string[]; summary: TeamImportPreviewSummary; rows: TeamImportPreviewRow[]; overrides: TeamImportOverride[]; assist?: { layoutEligible: boolean } }
type Batch = { id: string; fileName: string; status: string; createdAt: string; season: { name: string }; summaryJson: { preview?: { summary?: TeamImportPreviewSummary }; result?: TeamImportConfirmResult } }

export function upsertOverride(items: TeamImportOverride[], next: TeamImportOverride) { return [...items.filter((item) => !(item.rowNumber === next.rowNumber && item.columnLabel === next.columnLabel && item.field === next.field)), next].filter((item) => item.original !== item.value) }
export function resetRowOverrides(items: TeamImportOverride[], rowNumber: number) { return items.filter((item) => item.rowNumber !== rowNumber) }

type LayoutAssist = { batchId: string; fileHash: string; available: boolean; suggestion?: ImportAssistSuggestion; mapping?: TeamImportColumnMapping }

export function SupervisorImportClient({ assistEnabled = false }: { assistEnabled?: boolean }) {
  const inputRef = useRef<HTMLInputElement>(null)
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<Preview | null>(null); const [overrides, setOverrides] = useState<TeamImportOverride[]>([])
  const [result, setResult] = useState<TeamImportConfirmResult | null>(null); const [history, setHistory] = useState<Batch[]>([])
  const [columnMapping, setColumnMapping] = useState<TeamImportColumnMapping | null>(null); const [layoutAssist, setLayoutAssist] = useState<LayoutAssist | null>(null); const [repairSuggestions, setRepairSuggestions] = useState<ImportAssistSuggestion[]>([])
  const [loading, setLoading] = useState(false); const [historyLoading, setHistoryLoading] = useState(true); const [error, setError] = useState(''); const [confirmOpen, setConfirmOpen] = useState(false)
  const loadHistory = useCallback(async () => { try { setHistory((await getSupervisorRosterHistory<{ batches: Batch[] }>()).batches) } catch (err) { setError(err instanceof Error ? err.message : 'Could not load import history') } finally { setHistoryLoading(false) } }, [])
  useEffect(() => { void loadHistory() }, [loadHistory])
  const chooseFile = (next: File | null) => { if (!next) return; if (!/\.(xlsx|csv)$/i.test(next.name)) return toast.error('Choose an .xlsx or .csv file'); setFile(next); setPreview(null); setOverrides([]); setColumnMapping(null); setLayoutAssist(null); setRepairSuggestions([]); setResult(null); setError('') }
  const recheck = async (nextOverrides = overrides, nextMapping = columnMapping) => { if (!file) throw new Error('Choose a roster first'); setLoading(true); setError(''); try { const identity = preview ?? layoutAssist; const next = await previewSupervisorRoster<Preview>(file, identity ? { batchId: identity.batchId, fileHash: identity.fileHash, overrides: nextOverrides, columnMapping: nextMapping } : { overrides: nextOverrides, columnMapping: nextMapping }); setPreview(next); setOverrides(next.overrides); return next } catch (err) { const message = err instanceof Error ? err.message : 'Preview failed'; setError(message); throw err } finally { setLoading(false) } }
  const prepareConfirm = async () => { try { const checked = await recheck(); if (!checked.summary.validRows) return toast.error('Fix at least one team before confirming'); setConfirmOpen(true) } catch {} }
  const runConfirm = async () => { if (!file || !preview) return; setLoading(true); setError(''); try { const checked = await previewSupervisorRoster<Preview>(file, { batchId: preview.batchId, fileHash: preview.fileHash, overrides, columnMapping }); setPreview(checked); const next = await confirmSupervisorRoster<TeamImportConfirmResult>(checked.batchId, checked.fileHash, file, overrides, columnMapping); setResult(next); setConfirmOpen(false); await loadHistory(); toast.success('Teams submitted for admin approval') } catch (err) { setError(err instanceof Error ? err.message : 'Import failed') } finally { setLoading(false) } }
  const saveOverrides = (updates: TeamImportOverride[]) => setOverrides((current) => updates.reduce(upsertOverride, current))
  const resetRow = async (rowNumber: number) => { const next = resetRowOverrides(overrides, rowNumber); setOverrides(next); try { await recheck(next) } catch {} }
  const getLayoutHelp = async () => { if (!file) return; setLoading(true); try { const identity = preview ?? layoutAssist; const next = await requestImportLayoutAssist<LayoutAssist>(file, identity ? { batchId: identity.batchId, fileHash: identity.fileHash } : undefined); setLayoutAssist(next); if (!next.available) toast.message('AI mapping help is temporarily unavailable') } catch (err) { toast.error(err instanceof Error ? err.message : 'AI mapping help is unavailable') } finally { setLoading(false) } }
  const decideLayout = async (accepted: boolean) => { if (!layoutAssist?.suggestion) return; setLoading(true); try { await recordImportAssistOutcome(layoutAssist.batchId, layoutAssist.suggestion.id, accepted ? 'ACCEPTED' : 'REJECTED'); if (accepted && layoutAssist.mapping) { setColumnMapping(layoutAssist.mapping); await recheck(overrides, layoutAssist.mapping) } setLayoutAssist(null) } catch (err) { toast.error(err instanceof Error ? err.message : 'Could not record the decision') } finally { setLoading(false) } }
  const getRepairHelp = async () => { if (!file || !preview) return; setLoading(true); try { const next = await requestImportRepairAssist<{ available: boolean; suggestions: ImportAssistSuggestion[] }>(file, { batchId: preview.batchId, fileHash: preview.fileHash, overrides, columnMapping }); setRepairSuggestions(next.suggestions); if (!next.available || !next.suggestions.length) toast.message('No AI repair suggestions are available') } catch (err) { toast.error(err instanceof Error ? err.message : 'AI repair help is unavailable') } finally { setLoading(false) } }
  const decideRepair = async (suggestion: ImportAssistSuggestion, accepted: boolean) => { if (!preview || !suggestion.rowNumber || !suggestion.columnLabel || !suggestion.field) return; setLoading(true); try { await recordImportAssistOutcome(preview.batchId, suggestion.id, accepted ? 'ACCEPTED' : 'REJECTED'); setRepairSuggestions((items) => items.filter((item) => item.id !== suggestion.id)); if (accepted) { const row = preview.rows.find((item) => item.rowNumber === suggestion.rowNumber); const person = suggestion.columnLabel === 'Corresponding Team Member' ? row?.submitter : row?.members.find((item) => item.provenance.endsWith(suggestion.columnLabel!)); const original = String(person?.[suggestion.field as 'firstName' | 'lastName' | 'email'] ?? ''); const next = upsertOverride(overrides, { rowNumber: suggestion.rowNumber, columnLabel: suggestion.columnLabel, field: suggestion.field, original, value: suggestion.suggestion }); setOverrides(next); await recheck(next) } } catch (err) { toast.error(err instanceof Error ? err.message : 'Could not apply the suggestion') } finally { setLoading(false) } }
  return <div className="space-y-6">
    <div><h1 className="font-display text-3xl font-semibold text-foreground">Import Teams</h1><p className="text-text-secondary">Upload a roster, review every match, and submit valid teams for admin approval.</p></div>
    {error && <AlertBanner variant="error">{error}</AlertBanner>}
    {!preview && !result && <Card><CardHeader><CardTitle className="font-display">1 · Upload roster</CardTitle><CardDescription>Excel and CSV files up to 10 MB are supported.</CardDescription></CardHeader><CardContent className="space-y-4">
      <Button variant="outline" asChild><a href="/api/supervisor/roster-import/template"><Download className="mr-2 h-4 w-4"/>Start from the template</a></Button>
      <button type="button" onClick={() => inputRef.current?.click()} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); chooseFile(event.dataTransfer.files[0] ?? null) }} className="flex min-h-44 w-full flex-col items-center justify-center rounded-xl border-2 border-dashed border-border bg-surface-secondary p-6 text-center focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><UploadCloud className="mb-3 h-10 w-10 text-primary"/><strong>{file?.name ?? 'Drop your roster here'}</strong><span className="mt-1 text-sm text-text-secondary">or choose a file</span></button>
      <input ref={inputRef} type="file" accept=".xlsx,.csv" className="sr-only" onChange={(event) => chooseFile(event.target.files?.[0] ?? null)}/><div className="flex flex-wrap gap-3"><Button onClick={() => void recheck()} disabled={!file || loading}>{loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : <FileSpreadsheet className="mr-2 h-4 w-4"/>}Preview roster</Button>{assistEnabled && file && error && <Button variant="outline" disabled={loading} onClick={() => void getLayoutHelp()}><Sparkles className="mr-2 h-4 w-4"/>Get AI mapping help</Button>}</div>
      {layoutAssist?.available && layoutAssist.mapping && <div className="rounded-lg border border-border bg-primary-soft p-4"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-primary"/><strong>AI-generated suggested mapping</strong><Badge variant="info">{Math.round((layoutAssist.suggestion?.confidence ?? 0) * 100)}% confidence</Badge></div><p className="mt-2 text-sm text-text-secondary">Header row {layoutAssist.mapping.headerRowIndex + 1} · {layoutAssist.mapping.columnMap.length} columns mapped. Applying it runs the standard preview validator.</p><div className="mt-3 flex gap-2"><Button size="sm" disabled={loading} onClick={() => void decideLayout(true)}>Apply mapping</Button><Button size="sm" variant="outline" disabled={loading} onClick={() => void decideLayout(false)}>Dismiss</Button></div></div>}
    </CardContent></Card>}
    {preview && !result && <div className="space-y-5"><Card><CardHeader><CardTitle className="font-display">2 · Review preview</CardTitle><CardDescription className="tabular-nums">{preview.summary.totalRows} teams · {preview.summary.accountsToProvision} new accounts · {preview.summary.existingAccounts} existing · {preview.summary.invalidRows} errors</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-2">{preview.fileWarnings.map((warning) => <AlertBanner key={warning} variant="warning">{warning}</AlertBanner>)}{assistEnabled && preview.assist?.layoutEligible && <Button variant="outline" disabled={loading} onClick={() => void getLayoutHelp()}><Sparkles className="mr-2 h-4 w-4"/>Get AI mapping help</Button>}{assistEnabled && (preview.summary.invalidRows > 0 || preview.summary.rowsWithWarnings > 0) && <Button variant="outline" disabled={loading} onClick={() => void getRepairHelp()}><Sparkles className="mr-2 h-4 w-4"/>Get AI repair suggestions</Button>}</CardContent></Card>
      {layoutAssist?.available && layoutAssist.mapping && <Card><CardHeader><CardTitle className="flex items-center gap-2 font-display"><Sparkles className="h-5 w-5 text-primary"/>AI-generated suggested mapping</CardTitle><CardDescription>{layoutAssist.mapping.columnMap.length} columns · {Math.round((layoutAssist.suggestion?.confidence ?? 0) * 100)}% confidence</CardDescription></CardHeader><CardContent className="flex gap-2"><Button size="sm" onClick={() => void decideLayout(true)}>Apply mapping</Button><Button size="sm" variant="outline" onClick={() => void decideLayout(false)}>Dismiss</Button></CardContent></Card>}
      <div className="grid items-stretch gap-4 xl:grid-cols-2">{preview.rows.map((row) => <RosterRow key={row.rowNumber} row={row} overrides={overrides} suggestions={repairSuggestions} onSuggestion={decideRepair} onSave={saveOverrides} onReset={() => void resetRow(row.rowNumber)}/>)}</div>
      <div className="sticky bottom-3 z-20 rounded-xl border border-border bg-surface p-4 shadow-lg"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-display font-semibold tabular-nums">{preview.summary.validRows} valid teams will be submitted</p><p className="text-sm text-text-secondary">Invalid rows are skipped; students are emailed only after approval.</p></div><div className="flex flex-col-reverse gap-3 sm:flex-row"><Button variant="outline" onClick={() => { setPreview(null); setOverrides([]) }}>Choose another file</Button><Button className="w-full sm:w-auto" disabled={loading} onClick={() => void prepareConfirm()}>Confirm import</Button><Button variant="outline" disabled={loading} onClick={() => void recheck()}>Re-check</Button></div></div></div>
    </div>}
    {result && <Card><CardHeader><CardTitle className="flex items-center gap-2 font-display"><CheckCircle2 className="h-6 w-6 text-success"/>Submitted for admin approval</CardTitle><CardDescription className="tabular-nums">{result.summary.teamsCreated} teams created · {result.summary.skippedRows} rows skipped</CardDescription></CardHeader><CardContent><Button variant="outline" onClick={() => { setFile(null); setPreview(null); setOverrides([]); setResult(null) }}>Import another roster</Button></CardContent></Card>}
    <History history={history} loading={historyLoading}/>
    <ConfirmDialog open={confirmOpen} onOpenChange={setConfirmOpen} title="Submit valid teams for approval?" description={`${preview?.summary.validRows ?? 0} valid teams will be created as pending approval. Invalid rows will be skipped.`} confirmLabel="Submit for approval" loading={loading} onConfirm={runConfirm}/>
  </div>
}

function RosterRow({ row, overrides, suggestions, onSuggestion, onSave, onReset }: { row: TeamImportPreviewRow; overrides: TeamImportOverride[]; suggestions: ImportAssistSuggestion[]; onSuggestion: (suggestion: ImportAssistSuggestion, accepted: boolean) => void; onSave: (items: TeamImportOverride[]) => void; onReset: () => void }) {
  const status = !row.valid ? 'error' : row.warningCount ? 'warnings' : 'ready'; const icon = status === 'error' ? <XCircle className="h-3.5 w-3.5"/> : <CheckCircle2 className="h-3.5 w-3.5"/>
  return <Card className="flex h-full flex-col"><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle className="font-display">{row.teamName || row.teamExternalId}</CardTitle><CardDescription className="font-mono text-sm tabular-nums">Row {row.rowNumber} · {row.teamExternalId}</CardDescription></div><Badge variant={status === 'error' ? 'error' : status === 'warnings' ? 'warning' : 'success'} className="gap-1">{icon}{status}</Badge></div><TeamEditor row={row} overrides={overrides} onSave={onSave}/></CardHeader><CardContent className="flex flex-1 flex-col gap-3"><PersonEditor row={row} person={row.submitter} label="Corresponding Team Member" submitter overrides={overrides} suggestions={suggestions} onSuggestion={onSuggestion} onSave={onSave}/>{row.members.map((person) => { const label = (person.provenance.split(' · ')[1] || 'Additional Member 1') as TeamImportOverride['columnLabel']; return <PersonEditor key={person.provenance} row={row} person={person} label={label} overrides={overrides} suggestions={suggestions} onSuggestion={onSuggestion} onSave={onSave}/> })}<div className="mt-auto"><Button variant="outline" size="sm" onClick={onReset} disabled={!overrides.some((item) => item.rowNumber === row.rowNumber)}><RotateCcw className="mr-2 h-3.5 w-3.5"/>Reset row</Button></div>{(row.errors.length > 0 || row.warnings.length > 0) && <div className="-mx-6 -mb-6 space-y-2 border-t border-border bg-surface-secondary p-4">{row.errors.map((issue) => <ImportIssue key={issue} issue={issue} error/>)}{row.warnings.map((issue) => <ImportIssue key={issue} issue={issue}/>)}</div>}</CardContent></Card>
}
function TeamEditor({ row, overrides, onSave }: { row: TeamImportPreviewRow; overrides: TeamImportOverride[]; onSave: (items: TeamImportOverride[]) => void }) { return <InlineEditor label="Edit team" fields={[['teamName', row.teamName], ['teamExternalId', row.teamExternalId]]} edited={overrides} rowNumber={row.rowNumber} columnLabel="Team" onSave={onSave}/> }
function PersonEditor({ row, person, label, submitter, overrides, suggestions, onSuggestion, onSave }: { row: TeamImportPreviewRow; person: TeamImportPreviewRow['submitter']; label: TeamImportOverride['columnLabel']; submitter?: boolean; overrides: TeamImportOverride[]; suggestions: ImportAssistSuggestion[]; onSuggestion: (suggestion: ImportAssistSuggestion, accepted: boolean) => void; onSave: (items: TeamImportOverride[]) => void }) { const mine = suggestions.filter((item) => item.rowNumber === row.rowNumber && item.columnLabel === label); return <div className="rounded-lg bg-surface-secondary p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="font-medium">{person.firstName} {person.lastName}</p><p className="break-all font-mono text-sm tabular-nums text-text-secondary">{person.email || 'Email required'}</p><p className="mt-1 font-mono text-xs tabular-nums text-text-muted">{person.provenance}</p></div><div className="flex shrink-0 flex-col items-end gap-1">{submitter && <Badge variant="info">Submitter</Badge>}{person.email && <Badge variant={person.willBeCreated ? 'warning' : 'neutral'}>{person.willBeCreated ? 'Will be created' : 'Existing account'}</Badge>}</div></div>{mine.map((suggestion) => <div key={suggestion.id} className="mt-3 rounded-md border border-border bg-primary-soft p-3 text-sm"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-primary"/><strong>AI-generated</strong><Badge variant="info">{Math.round(suggestion.confidence * 100)}%</Badge></div><p className="mt-1">Suggested {suggestion.field}: <strong>{suggestion.suggestion}</strong></p><p className="text-text-secondary">{suggestion.reason}</p><div className="mt-2 flex flex-wrap gap-2"><Button size="sm" onClick={() => onSuggestion(suggestion, true)}>Accept</Button><Button size="sm" variant="outline" onClick={() => onSuggestion(suggestion, true)}>Edit</Button><Button size="sm" variant="ghost" onClick={() => onSuggestion(suggestion, false)}>Dismiss</Button></div></div>)}<InlineEditor label={`Edit ${label}`} fields={[['firstName', person.firstName], ['lastName', person.lastName], ['email', person.email]]} edited={overrides} rowNumber={row.rowNumber} columnLabel={label} onSave={onSave}/></div> }
function InlineEditor({ label, fields, edited, rowNumber, columnLabel, onSave }: { label: string; fields: Array<[TeamImportOverride['field'], string]>; edited: TeamImportOverride[]; rowNumber: number; columnLabel: TeamImportOverride['columnLabel']; onSave: (items: TeamImportOverride[]) => void }) { const [open, setOpen] = useState(false); const findEdit = (field: TeamImportOverride['field']) => edited.find((item) => item.rowNumber === rowNumber && item.columnLabel === columnLabel && item.field === field); const current = Object.fromEntries(fields.map(([field, value]) => [field, findEdit(field)?.value ?? value])); const [draft, setDraft] = useState<Record<string, string>>(current); const save = () => { onSave(fields.map(([field, value]) => ({ rowNumber, columnLabel, field, original: findEdit(field)?.original ?? value, value: draft[field] ?? '' }))); setOpen(false) }; if (!open) return <div className="mt-2 flex items-center gap-2"><Button variant="ghost" size="sm" aria-label={label} onClick={() => { setDraft(current); setOpen(true) }}><Pencil className="mr-1 h-3.5 w-3.5"/>Edit</Button>{fields.some(([field]) => Boolean(findEdit(field))) && <Badge variant="info">edited</Badge>}</div>; return <div className="mt-3 grid gap-2" onKeyDown={(event) => { if (event.key === 'Escape') setOpen(false); if (event.key === 'Enter') { event.preventDefault(); save() } }}>{fields.map(([field, value]) => { const original = findEdit(field)?.original ?? value; return <label key={field} className="text-xs font-medium capitalize">{field.replace(/([A-Z])/g, ' $1')}<Input value={draft[field] ?? ''} onChange={(event) => setDraft({ ...draft, [field]: event.target.value })}/>{draft[field] !== original && <span className="text-text-muted">Original: <span className="line-through">{original || '(blank)'}</span></span>}</label> })}<div className="flex gap-2"><Button size="sm" onClick={save}>Save</Button><Button size="sm" variant="outline" onClick={() => setOpen(false)}>Cancel</Button></div></div> }
function ImportIssue({ issue, error = false }: { issue: string; error?: boolean }) { const split = issue.indexOf(':'); return <p className={`flex gap-2 text-sm ${error ? 'text-error' : 'text-warning'}`}><AlertCircle className="mt-0.5 h-4 w-4 shrink-0"/><span>{split > 0 && <strong className="font-mono text-xs">{issue.slice(0, split)}:</strong>} {split > 0 ? issue.slice(split + 1) : issue}</span></p> }
function History({ history, loading }: { history: Batch[]; loading: boolean }) { const row = (batch: Batch) => ({ count: batch.summaryJson.result?.summary.teamsCreated ?? batch.summaryJson.preview?.summary?.totalRows ?? 0, date: new Date(batch.createdAt).toISOString().slice(0, 10) }); return <Card><CardHeader><CardTitle className="font-display">Import history</CardTitle><CardDescription>Your 25 most recent roster batches</CardDescription></CardHeader><CardContent>{loading ? <Loader2 className="h-5 w-5 animate-spin text-primary"/> : history.length ? <><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead><tr className="border-b border-border text-text-secondary"><th className="p-3">File</th><th className="p-3">Season</th><th className="p-3 text-right">Teams</th><th className="p-3">Status</th><th className="p-3 text-right">Uploaded</th></tr></thead><tbody>{history.map((batch) => <tr key={batch.id} className="border-b border-border"><td className="p-3 font-medium">{batch.fileName}</td><td className="p-3">{batch.season.name}</td><td className="p-3 text-right tabular-nums">{row(batch).count}</td><td className="p-3"><BatchStatus status={batch.status}/></td><td className="p-3 text-right font-mono text-sm tabular-nums">{row(batch).date}</td></tr>)}</tbody></table></div><div className="grid gap-3 md:hidden">{history.map((batch) => <div key={batch.id} className="rounded-lg border border-border bg-surface-secondary p-4"><div className="flex items-start justify-between gap-3"><p className="break-all font-medium">{batch.fileName}</p><BatchStatus status={batch.status}/></div><dl className="mt-3 grid grid-cols-2 gap-2 text-sm"><div><dt className="text-text-secondary">Season</dt><dd>{batch.season.name}</dd></div><div className="text-right"><dt className="text-text-secondary">Teams</dt><dd className="tabular-nums">{row(batch).count}</dd></div><div className="col-span-2 text-right"><dt className="sr-only">Uploaded</dt><dd className="font-mono text-text-secondary tabular-nums">{row(batch).date}</dd></div></dl></div>)}</div></> : <div className="py-8 text-center"><Users className="mx-auto mb-2 h-9 w-9 text-text-muted"/><p>No roster imports yet.</p><Button variant="outline" className="mt-3" asChild><a href="/api/supervisor/roster-import/template"><Download className="mr-2 h-4 w-4"/>Start from the template</a></Button></div>}</CardContent></Card> }
function BatchStatus({ status }: { status: string }) { return <Badge variant={status === 'COMPLETED' ? 'success' : status === 'CONFIRMED' ? 'warning' : 'neutral'}>{status.toLowerCase()}</Badge> }
