'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import { AlertCircle, CheckCircle2, Download, FileSpreadsheet, Loader2, Pencil, RotateCcw, Sparkles, Trash2, Undo2, UploadCloud, Users, XCircle } from 'lucide-react'
import { toast } from 'sonner'
import { previewSupervisorRoster, confirmSupervisorRoster, downloadSupervisorRosterTemplate, getSupervisorRosterHistory, recordImportAssistOutcome, requestImportExplanation, requestImportLayoutAssist, requestImportRepairAssist, withdrawSupervisorImportedTeam } from '@/features/teams/roster-import-api'
import type { ImportAssistSuggestion, TeamImportColumnMapping, TeamImportConfirmResult, TeamImportMetadata, TeamImportOverride, TeamImportPreviewRow, TeamImportPreviewSummary } from '@/lib/team-import/types'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { AlertBanner } from '@/components/ui/alert-banner'
import { ConfirmDialog } from '@/components/ui/confirm-dialog'
import { Input } from '@/components/ui/input'
import type { ImportDiagnostic } from '@/lib/team-import/diagnostics'

type Preview = { batchId: string; fileHash: string; fileName: string; metadata: TeamImportMetadata; fileWarnings: string[]; summary: TeamImportPreviewSummary; rows: TeamImportPreviewRow[]; overrides: TeamImportOverride[]; excludedRowNumbers: number[]; assist?: { layoutEligible: boolean } }
type BatchTeam = { id: string; name: string; externalTeamId: string; status: string }
type Batch = { id: string; fileName: string; status: string; createdAt: string; season: { name: string }; teams: BatchTeam[]; summaryJson: { preview?: { summary?: TeamImportPreviewSummary }; result?: TeamImportConfirmResult } }

export function upsertOverride(items: TeamImportOverride[], next: TeamImportOverride) { return [...items.filter((item) => !(item.rowNumber === next.rowNumber && item.columnLabel === next.columnLabel && item.field === next.field)), next].filter((item) => item.original !== item.value) }
export function resetRowOverrides(items: TeamImportOverride[], rowNumber: number) { return items.filter((item) => item.rowNumber !== rowNumber) }

type LayoutAssist = { batchId: string; fileHash: string; available: boolean; suggestion?: ImportAssistSuggestion; mapping?: TeamImportColumnMapping }

function importErrorMessage(error: unknown) {
  const message = error instanceof Error ? error.message : 'Preview failed'
  if (/missing (?:the )?first sheet reference|missing sheet metadata|does not contain any sheets/i.test(message)) {
    return 'We could not read the worksheets in this Excel file. The file may be damaged or may only have been renamed to .xlsx. Open it in Excel or Google Sheets, save or download a new Excel Workbook (.xlsx), then upload the new copy. You can also download a fresh RevME template below.'
  }
  return message
}

export function SupervisorImportClient({ assistEnabled = false, seasonAvailable = true, registrationOpen = true }: { assistEnabled?: boolean; seasonAvailable?: boolean; registrationOpen?: boolean }) {
  const inputRef = useRef<HTMLInputElement>(null)
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<Preview | null>(null); const [overrides, setOverrides] = useState<TeamImportOverride[]>([])
  const [excludedRowNumbers, setExcludedRowNumbers] = useState<number[]>([])
  const [result, setResult] = useState<TeamImportConfirmResult | null>(null); const [history, setHistory] = useState<Batch[]>([])
  const [columnMapping, setColumnMapping] = useState<TeamImportColumnMapping | null>(null); const [layoutAssist, setLayoutAssist] = useState<LayoutAssist | null>(null); const [repairSuggestions, setRepairSuggestions] = useState<ImportAssistSuggestion[]>([])
  const [loading, setLoading] = useState(false); const [historyLoading, setHistoryLoading] = useState(true); const [error, setError] = useState(''); const [confirmOpen, setConfirmOpen] = useState(false)
  const [explanation, setExplanation] = useState<{ summary: string; nextSteps: string[] } | null>(null)
  const [filter, setFilter] = useState<'all' | 'attention' | 'warnings' | 'ready' | 'removed'>('all')
  const [mappingRows, setMappingRows] = useState<string[][] | null>(null)
  const loadHistory = useCallback(async () => { try { setHistory((await getSupervisorRosterHistory<{ batches: Batch[] }>()).batches) } catch (err) { setError(err instanceof Error ? err.message : 'Could not load import history') } finally { setHistoryLoading(false) } }, [])
  useEffect(() => { void loadHistory() }, [loadHistory])
  const resetSelectedFile = () => {
    setFile(null); setPreview(null); setOverrides([]); setExcludedRowNumbers([]); setColumnMapping(null); setMappingRows(null); setLayoutAssist(null); setRepairSuggestions([]); setExplanation(null); setResult(null); setError(''); setConfirmOpen(false); setFilter('all')
    if (inputRef.current) inputRef.current.value = ''
  }
  const openFilePicker = () => {
    if (!inputRef.current) return
    inputRef.current.value = ''
    inputRef.current.click()
  }
  const chooseFile = (next: File | null) => {
    if (!next) return
    if (!/\.(xlsx|csv)$/i.test(next.name)) return toast.error('Choose an .xlsx or .csv file')
    resetSelectedFile()
    setFile(next)
  }
  const recheck = async (nextOverrides = overrides, nextMapping = columnMapping, nextExcluded = excludedRowNumbers) => { if (!file) throw new Error('Choose a roster first'); setLoading(true); setError(''); try { const identity = preview ?? layoutAssist; const next = await previewSupervisorRoster<Preview>(file, identity ? { batchId: identity.batchId, fileHash: identity.fileHash, overrides: nextOverrides, columnMapping: nextMapping, excludedRowNumbers: nextExcluded } : { overrides: nextOverrides, columnMapping: nextMapping, excludedRowNumbers: nextExcluded }); setPreview(next); setMappingRows(null); setOverrides(next.overrides); setExcludedRowNumbers(next.excludedRowNumbers); if (!next.assist) { setLayoutAssist(null); setRepairSuggestions([]); setExplanation(null) } return next } catch (err) { const details = (err as Error & { details?: { mappingContext?: { rows?: string[][] } } })?.details; setMappingRows(details?.mappingContext?.rows ?? null); setError(importErrorMessage(err)); throw err } finally { setLoading(false) } }
  const prepareConfirm = async () => { try { const checked = await recheck(); if (!checked.summary.validRows) return toast.error('Fix at least one team before confirming'); setConfirmOpen(true) } catch {} }
  const runConfirm = async () => { if (!file || !preview) return; setLoading(true); setError(''); try { const checked = await previewSupervisorRoster<Preview>(file, { batchId: preview.batchId, fileHash: preview.fileHash, overrides, columnMapping, excludedRowNumbers }); setPreview(checked); const next = await confirmSupervisorRoster<TeamImportConfirmResult>(checked.batchId, checked.fileHash, file, overrides, columnMapping, excludedRowNumbers); setResult(next); setConfirmOpen(false); await loadHistory(); toast.success('Teams submitted for admin approval') } catch (err) { setError(err instanceof Error ? err.message : 'Import failed') } finally { setLoading(false) } }
  const saveOverrides = (updates: TeamImportOverride[]) => setOverrides((current) => updates.reduce(upsertOverride, current))
  const resetRow = async (rowNumber: number) => { const next = resetRowOverrides(overrides, rowNumber); setOverrides(next); try { await recheck(next) } catch {} }
  const toggleExcluded = async (rowNumber: number, exclude: boolean) => { const nextExcluded = exclude ? [...excludedRowNumbers, rowNumber].sort((a, b) => a - b) : excludedRowNumbers.filter((item) => item !== rowNumber); const nextOverrides = exclude ? resetRowOverrides(overrides, rowNumber) : overrides; setExcludedRowNumbers(nextExcluded); setOverrides(nextOverrides); setRepairSuggestions((items) => items.filter((item) => item.rowNumber !== rowNumber)); try { await recheck(nextOverrides, columnMapping, nextExcluded) } catch {} }
  const getLayoutHelp = async () => { if (!file) return; setLoading(true); try { const identity = preview ?? layoutAssist; const next = await requestImportLayoutAssist<LayoutAssist>(file, identity ? { batchId: identity.batchId, fileHash: identity.fileHash } : undefined); setLayoutAssist(next); if (!next.available) toast.message('AI mapping help is temporarily unavailable') } catch (err) { toast.error(err instanceof Error ? err.message : 'AI mapping help is unavailable') } finally { setLoading(false) } }
  const decideLayout = async (accepted: boolean) => { if (!layoutAssist?.suggestion) return; setLoading(true); try { await recordImportAssistOutcome(layoutAssist.batchId, layoutAssist.suggestion.id, accepted ? 'ACCEPTED' : 'REJECTED'); if (accepted && layoutAssist.mapping) { setColumnMapping(layoutAssist.mapping); await recheck(overrides, layoutAssist.mapping) } setLayoutAssist(null) } catch (err) { toast.error(err instanceof Error ? err.message : 'Could not record the decision') } finally { setLoading(false) } }
  const getRepairHelp = async () => { if (!file || !preview) return; setLoading(true); try { const next = await requestImportRepairAssist<{ available: boolean; suggestions: ImportAssistSuggestion[] }>(file, { batchId: preview.batchId, fileHash: preview.fileHash, overrides, columnMapping, excludedRowNumbers }); setRepairSuggestions(next.suggestions); if (!next.available || !next.suggestions.length) toast.message('No AI repair suggestions are available') } catch (err) { toast.error(err instanceof Error ? err.message : 'AI repair help is unavailable') } finally { setLoading(false) } }
  const explainIssues = async () => { if (!file || !preview) return; setLoading(true); try { const next = await requestImportExplanation<{ available: boolean; explanation?: { summary: string; nextSteps: string[] } }>(file, { batchId: preview.batchId, fileHash: preview.fileHash, overrides, columnMapping, excludedRowNumbers }); setExplanation(next.explanation ?? null); if (!next.available) toast.message('AI explanation is temporarily unavailable. The guidance below is still available.') } catch (err) { toast.error(err instanceof Error ? err.message : 'AI explanation is unavailable') } finally { setLoading(false) } }
  const decideRepair = async (suggestion: ImportAssistSuggestion, accepted: boolean, editedValue?: string) => { if (!preview || !suggestion.rowNumber || !suggestion.columnLabel || !suggestion.field) return; setLoading(true); try { await recordImportAssistOutcome(preview.batchId, suggestion.id, accepted ? 'ACCEPTED' : 'REJECTED'); setRepairSuggestions((items) => items.filter((item) => item.id !== suggestion.id)); if (accepted) { const row = preview.rows.find((item) => item.rowNumber === suggestion.rowNumber); const person = suggestion.columnLabel === 'Corresponding Team Member' ? row?.submitter : row?.members.find((item) => item.provenance.endsWith(suggestion.columnLabel!)); const original = suggestion.sourceValue ?? (suggestion.columnLabel === 'Team' ? String(row?.[suggestion.field as 'teamName' | 'teamExternalId'] ?? '') : String(person?.[suggestion.field as 'firstName' | 'lastName' | 'email'] ?? '')); const next = upsertOverride(overrides, { rowNumber: suggestion.rowNumber, columnLabel: suggestion.columnLabel, field: suggestion.field, original, value: editedValue ?? suggestion.suggestion }); setOverrides(next); await recheck(next) } } catch (err) { toast.error(err instanceof Error ? err.message : 'Could not apply the suggestion') } finally { setLoading(false) } }
  const visibleRows = preview?.rows.filter((row) => filter === 'all' || (filter === 'attention' && !row.valid && !row.excluded) || (filter === 'warnings' && row.valid && row.warningCount > 0) || (filter === 'ready' && row.valid && !row.warningCount) || (filter === 'removed' && row.excluded)) ?? []
  const fixNext = () => { const row = preview?.rows.find((item) => !item.excluded && !item.valid); if (row) document.getElementById(`roster-row-${row.rowNumber}`)?.scrollIntoView({ behavior: 'smooth', block: 'center' }) }
  return <div className="space-y-6">
    <div><h1 className="font-display text-3xl font-semibold text-foreground">Import Teams</h1><p className="text-text-secondary">Upload a roster, review every match, and submit valid teams for admin approval.</p></div>
    {!seasonAvailable && <AlertBanner variant="warning"><strong>Team import is not available yet.</strong> An administrator must create or activate a competition season. Upload and template actions are disabled until then.</AlertBanner>}
    {seasonAvailable && !registrationOpen && <AlertBanner variant="warning"><strong>Team registration is closed.</strong> Contact an administrator if another roster must be imported.</AlertBanner>}
    {error && <AlertBanner variant="error"><div className="space-y-2"><p className="font-medium">We could not preview this roster</p><p>{error}</p>{!preview && <div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" disabled={!seasonAvailable || !registrationOpen} onClick={openFilePicker}><UploadCloud className="mr-2 h-4 w-4"/>Choose another file</Button><Button variant="outline" size="sm" disabled={!seasonAvailable || !registrationOpen} onClick={() => void downloadSupervisorRosterTemplate().catch((downloadError) => setError(downloadError instanceof Error ? downloadError.message : 'Template download failed'))}><Download className="mr-2 h-4 w-4"/>Download a fresh template</Button></div>}</div></AlertBanner>}
    {!preview && !result && <Card><CardHeader><CardTitle className="font-display">1 · Upload roster</CardTitle><CardDescription>Excel and CSV files up to 10 MB are supported.</CardDescription></CardHeader><CardContent className="space-y-4">
      <Button variant="outline" disabled={!seasonAvailable || !registrationOpen} onClick={() => void downloadSupervisorRosterTemplate().catch((error) => setError(error instanceof Error ? error.message : 'Template download failed'))}><Download className="mr-2 h-4 w-4"/>Start from the template</Button>
      <button type="button" disabled={!seasonAvailable || !registrationOpen} onClick={openFilePicker} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); chooseFile(event.dataTransfer.files[0] ?? null) }} className="flex min-h-44 w-full flex-col items-center justify-center rounded-xl border-2 border-dashed border-border bg-surface-secondary p-6 text-center focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-60"><UploadCloud className="mb-3 h-10 w-10 text-primary"/><strong>{file?.name ?? 'Drop your roster here'}</strong><span className="mt-1 text-sm text-text-secondary">or choose a file</span><span className="mt-2 text-xs text-text-muted">Selecting a file checks its type. Preview validates the workbook contents before anything is imported.</span></button>
      <input ref={inputRef} type="file" accept=".xlsx,.csv" className="sr-only" onChange={(event) => chooseFile(event.target.files?.[0] ?? null)}/><div className="flex flex-wrap gap-3"><Button onClick={() => void recheck().catch(() => undefined)} disabled={!file || loading}>{loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : <FileSpreadsheet className="mr-2 h-4 w-4"/>}Preview roster</Button>{file && <Button variant="outline" disabled={loading} onClick={openFilePicker}><UploadCloud className="mr-2 h-4 w-4"/>Choose another file</Button>}{assistEnabled && file && error && <Button variant="outline" disabled={loading} onClick={() => void getLayoutHelp()}><Sparkles className="mr-2 h-4 w-4"/>Get AI mapping help</Button>}</div>
      {layoutAssist?.available && layoutAssist.mapping && <div className="rounded-lg border border-border bg-primary-soft p-4"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-primary"/><strong>AI-generated suggested mapping</strong><Badge variant="info">{Math.round((layoutAssist.suggestion?.confidence ?? 0) * 100)}% confidence</Badge></div><p className="mt-2 text-sm text-text-secondary">Header row {layoutAssist.mapping.headerRowIndex + 1} · {layoutAssist.mapping.columnMap.length} columns mapped. Applying it runs the standard preview validator.</p><div className="mt-3 flex gap-2"><Button size="sm" disabled={loading} onClick={() => void decideLayout(true)}>Apply mapping</Button><Button size="sm" variant="outline" disabled={loading} onClick={() => void decideLayout(false)}>Dismiss</Button></div></div>}
      {mappingRows && (
        <ManualMapping rows={mappingRows} loading={loading} onApply={(mapping) => { setColumnMapping(mapping); void recheck(overrides, mapping).catch(() => undefined) }}/>
      )}
    </CardContent></Card>}
    {preview && !result && <div className="space-y-5"><Card><CardHeader><CardTitle className="font-display">2 · Review preview</CardTitle><CardDescription className="tabular-nums">{preview.summary.totalRows} teams · {preview.summary.accountsToProvision} new accounts · {preview.summary.existingAccounts} existing · {preview.summary.invalidRows} errors</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-2">{preview.fileWarnings.map((warning) => <AlertBanner key={warning} variant="warning">{warning}</AlertBanner>)}{assistEnabled && preview.assist?.layoutEligible && <Button variant="outline" disabled={loading} onClick={() => void getLayoutHelp()}><Sparkles className="mr-2 h-4 w-4"/>Let AI map these columns</Button>}{assistEnabled && preview.assist && (preview.summary.invalidRows > 0 || preview.summary.rowsWithWarnings > 0) && <><Button variant="outline" disabled={loading} onClick={() => void explainIssues()}><Sparkles className="mr-2 h-4 w-4"/>Explain these issues</Button><Button variant="outline" disabled={loading} onClick={() => void getRepairHelp()}><Sparkles className="mr-2 h-4 w-4"/>Help me fix this</Button></>}</CardContent></Card>
      {explanation && <AlertBanner variant="info"><div><strong>AI-assisted explanation</strong><p className="mt-1">{explanation.summary}</p><ol className="mt-2 list-decimal space-y-1 pl-5">{explanation.nextSteps.map((step) => <li key={step}>{step}</li>)}</ol><p className="mt-2 text-xs">RevME validation remains the final authority.</p></div></AlertBanner>}
      {layoutAssist?.available && layoutAssist.mapping && <Card><CardHeader><CardTitle className="flex items-center gap-2 font-display"><Sparkles className="h-5 w-5 text-primary"/>AI-generated suggested mapping</CardTitle><CardDescription>{layoutAssist.mapping.columnMap.length} columns · {Math.round((layoutAssist.suggestion?.confidence ?? 0) * 100)}% confidence</CardDescription></CardHeader><CardContent className="flex gap-2"><Button size="sm" onClick={() => void decideLayout(true)}>Apply mapping</Button><Button size="sm" variant="outline" onClick={() => void decideLayout(false)}>Dismiss</Button></CardContent></Card>}
      <div className="flex flex-wrap items-center gap-2" aria-label="Filter roster rows">{([['all','All'],['attention','Needs attention'],['warnings','Warnings'],['ready','Ready'],['removed','Removed']] as const).map(([value,label]) => <Button key={value} size="sm" variant={filter === value ? 'default' : 'outline'} onClick={() => setFilter(value)}>{label}</Button>)}{preview.summary.invalidRows > 0 && <Button size="sm" variant="outline" onClick={fixNext}>Fix next issue</Button>}</div>
      <p className="sr-only" aria-live="polite">Showing {visibleRows.length} of {preview.rows.length} roster rows. {repairSuggestions.length} AI suggestions available.</p>
      <div className="grid items-stretch gap-4 xl:grid-cols-2">{visibleRows.map((row) => <div id={`roster-row-${row.rowNumber}`} key={row.rowNumber}><RosterRow row={row} overrides={overrides} suggestions={repairSuggestions} decisionsDisabled={loading} onSuggestion={decideRepair} onSave={saveOverrides} onReset={() => void resetRow(row.rowNumber)} onToggleExcluded={(exclude) => void toggleExcluded(row.rowNumber, exclude)}/></div>)}</div>
      <div className="sticky bottom-3 z-20 rounded-xl border border-border bg-surface p-4 shadow-lg"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-display font-semibold tabular-nums">{preview.summary.validRows} valid teams will be submitted</p><p className="text-sm text-text-secondary">{preview.summary.invalidRows} invalid · {preview.summary.excludedRows} removed · students are emailed only after approval.</p></div><div className="flex flex-col-reverse gap-3 sm:flex-row"><Button variant="outline" disabled={loading} onClick={() => { resetSelectedFile(); queueMicrotask(openFilePicker) }}>Choose another file</Button><Button className="w-full sm:w-auto" disabled={loading || preview.summary.validRows === 0} onClick={() => void prepareConfirm()}>Confirm import</Button><Button variant="outline" disabled={loading} onClick={() => void recheck()}>Re-check</Button></div></div></div>
    </div>}
    {result && <Card><CardHeader><CardTitle className="flex items-center gap-2 font-display"><CheckCircle2 className="h-6 w-6 text-success"/>Submitted for admin approval</CardTitle><CardDescription className="tabular-nums">{result.summary.teamsCreated} teams created · {result.summary.skippedRows} rows skipped</CardDescription></CardHeader><CardContent><Button variant="outline" onClick={() => { resetSelectedFile(); queueMicrotask(openFilePicker) }}>Import another roster</Button></CardContent></Card>}
    <History history={history} loading={historyLoading} onChanged={loadHistory}/>
    <ConfirmDialog open={confirmOpen} onOpenChange={setConfirmOpen} title="Submit valid teams for approval?" description={`${preview?.summary.validRows ?? 0} valid teams will be created as pending approval. ${preview?.summary.invalidRows ?? 0} invalid and ${preview?.summary.excludedRows ?? 0} removed rows will be skipped.`} confirmLabel="Submit for approval" loading={loading} onConfirm={runConfirm}/>
  </div>
}

function RosterRow({ row, overrides, suggestions, decisionsDisabled, onSuggestion, onSave, onReset, onToggleExcluded }: { row: TeamImportPreviewRow; overrides: TeamImportOverride[]; suggestions: ImportAssistSuggestion[]; decisionsDisabled: boolean; onSuggestion: (suggestion: ImportAssistSuggestion, accepted: boolean, editedValue?: string) => void; onSave: (items: TeamImportOverride[]) => void; onReset: () => void; onToggleExcluded: (exclude: boolean) => void }) {
  if (row.excluded) return <Card className="border-dashed bg-surface-secondary"><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle className="font-display text-text-secondary">{row.teamName || row.teamExternalId}</CardTitle><CardDescription className="font-mono text-sm tabular-nums">Row {row.rowNumber} · removed from import</CardDescription></div><Badge variant="neutral">Removed</Badge></div></CardHeader><CardContent><Button variant="outline" size="sm" onClick={() => onToggleExcluded(false)}><Undo2 className="mr-2 h-3.5 w-3.5"/>Undo removal</Button></CardContent></Card>
  const status = !row.valid ? 'error' : row.warningCount ? 'warnings' : 'ready'; const icon = status === 'error' ? <XCircle className="h-3.5 w-3.5"/> : <CheckCircle2 className="h-3.5 w-3.5"/>
  return <Card className="flex h-full flex-col"><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle className="font-display">{row.teamName || row.teamExternalId}</CardTitle><CardDescription className="font-mono text-sm tabular-nums">Row {row.rowNumber} · {row.teamExternalId}</CardDescription></div><Badge variant={status === 'error' ? 'error' : status === 'warnings' ? 'warning' : 'success'} className="gap-1">{icon}{status}</Badge></div><TeamEditor row={row} overrides={overrides} suggestions={suggestions} decisionsDisabled={decisionsDisabled} onSuggestion={onSuggestion} onSave={onSave}/></CardHeader><CardContent className="flex flex-1 flex-col gap-3"><PersonEditor row={row} person={row.submitter} label="Corresponding Team Member" submitter overrides={overrides} suggestions={suggestions} decisionsDisabled={decisionsDisabled} onSuggestion={onSuggestion} onSave={onSave}/>{row.members.map((person) => { const label = (person.provenance.split(' · ')[1] || 'Additional Member 1') as TeamImportOverride['columnLabel']; return <PersonEditor key={person.provenance} row={row} person={person} label={label} overrides={overrides} suggestions={suggestions} decisionsDisabled={decisionsDisabled} onSuggestion={onSuggestion} onSave={onSave}/> })}<div className="mt-auto flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={onReset} disabled={decisionsDisabled || !overrides.some((item) => item.rowNumber === row.rowNumber)}><RotateCcw className="mr-2 h-3.5 w-3.5"/>Reset row</Button><Button variant="ghost" size="sm" className="text-error" disabled={decisionsDisabled} onClick={() => onToggleExcluded(true)}><Trash2 className="mr-1 h-3.5 w-3.5"/>Remove from import</Button></div>{row.diagnostics.length > 0 && <div className="-mx-6 -mb-6 space-y-2 border-t border-border bg-surface-secondary p-4">{row.diagnostics.map((diagnostic, index) => <ImportDiagnosticIssue key={`${diagnostic.code}-${diagnostic.provenance ?? index}`} diagnostic={diagnostic}/>)}</div>}</CardContent></Card>
}
function TeamEditor({ row, overrides, suggestions, decisionsDisabled, onSuggestion, onSave }: { row: TeamImportPreviewRow; overrides: TeamImportOverride[]; suggestions: ImportAssistSuggestion[]; decisionsDisabled: boolean; onSuggestion: SuggestionDecision; onSave: (items: TeamImportOverride[]) => void }) { const mine = suggestions.filter((item) => item.rowNumber === row.rowNumber && item.columnLabel === 'Team'); return <>{mine.map((suggestion) => <RepairSuggestion key={suggestion.id} suggestion={suggestion} disabled={decisionsDisabled} onDecision={onSuggestion}/>)}<InlineEditor label="Edit team" fields={[['teamName', row.teamName], ['teamExternalId', row.teamExternalId]]} edited={overrides} rowNumber={row.rowNumber} columnLabel="Team" onSave={onSave}/></> }
type SuggestionDecision = (suggestion: ImportAssistSuggestion, accepted: boolean, editedValue?: string) => void
function PersonEditor({ row, person, label, submitter, overrides, suggestions, decisionsDisabled, onSuggestion, onSave }: { row: TeamImportPreviewRow; person: TeamImportPreviewRow['submitter']; label: TeamImportOverride['columnLabel']; submitter?: boolean; overrides: TeamImportOverride[]; suggestions: ImportAssistSuggestion[]; decisionsDisabled: boolean; onSuggestion: SuggestionDecision; onSave: (items: TeamImportOverride[]) => void }) { const mine = suggestions.filter((item) => item.rowNumber === row.rowNumber && item.columnLabel === label); return <div className="rounded-lg bg-surface-secondary p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="font-medium">{person.firstName} {person.lastName}</p><p className="break-all font-mono text-sm tabular-nums text-text-secondary">{person.email || 'Email required'}</p><p className="mt-1 font-mono text-xs tabular-nums text-text-muted">{person.provenance}</p></div><div className="flex shrink-0 flex-col items-end gap-1">{submitter && <Badge variant="info">Submitter</Badge>}{person.email && <Badge variant={person.willBeCreated ? 'warning' : 'neutral'}>{person.willBeCreated ? 'Will be created' : 'Existing account'}</Badge>}</div></div>{mine.map((suggestion) => <RepairSuggestion key={suggestion.id} suggestion={suggestion} disabled={decisionsDisabled} onDecision={onSuggestion}/>)}<InlineEditor label={`Edit ${label}`} fields={[['firstName', person.firstName], ['lastName', person.lastName], ['email', person.email]]} edited={overrides} rowNumber={row.rowNumber} columnLabel={label} onSave={onSave}/></div> }
function RepairSuggestion({ suggestion, disabled, onDecision }: { suggestion: ImportAssistSuggestion; disabled: boolean; onDecision: SuggestionDecision }) { const [editing, setEditing] = useState(false); const [value, setValue] = useState(suggestion.suggestion); return <div className="mt-3 rounded-md border border-border bg-primary-soft p-3 text-sm"><div className="flex flex-wrap items-center gap-2"><Sparkles className="h-4 w-4 text-primary"/><strong>AI-generated suggestion</strong><Badge variant="info">{Math.round(suggestion.confidence * 100)}%</Badge></div><p className="mt-1">Suggested {suggestion.field}: <strong>{suggestion.suggestion}</strong></p><p className="text-text-secondary">{suggestion.reason}</p>{editing ? <div className="mt-2 space-y-2"><label className="block text-xs font-medium">Review and edit<Input disabled={disabled} value={value} onChange={(event) => setValue(event.target.value)}/></label><div className="flex gap-2"><Button size="sm" disabled={disabled || !value.trim()} onClick={() => onDecision(suggestion, true, value)}>Save edited value</Button><Button size="sm" variant="outline" disabled={disabled} onClick={() => { setValue(suggestion.suggestion); setEditing(false) }}>Cancel</Button></div></div> : <div className="mt-2 flex flex-wrap gap-2"><Button size="sm" disabled={disabled} onClick={() => onDecision(suggestion, true)}>Accept</Button><Button size="sm" variant="outline" disabled={disabled} onClick={() => setEditing(true)}>Edit</Button><Button size="sm" variant="ghost" disabled={disabled} onClick={() => onDecision(suggestion, false)}>Dismiss</Button></div>}</div> }
function InlineEditor({ label, fields, edited, rowNumber, columnLabel, onSave }: { label: string; fields: Array<[TeamImportOverride['field'], string]>; edited: TeamImportOverride[]; rowNumber: number; columnLabel: TeamImportOverride['columnLabel']; onSave: (items: TeamImportOverride[]) => void }) { const [open, setOpen] = useState(false); const findEdit = (field: TeamImportOverride['field']) => edited.find((item) => item.rowNumber === rowNumber && item.columnLabel === columnLabel && item.field === field); const current = Object.fromEntries(fields.map(([field, value]) => [field, findEdit(field)?.value ?? value])); const [draft, setDraft] = useState<Record<string, string>>(current); const save = () => { onSave(fields.map(([field, value]) => ({ rowNumber, columnLabel, field, original: findEdit(field)?.original ?? value, value: draft[field] ?? '' }))); setOpen(false) }; if (!open) return <div className="mt-2 flex items-center gap-2"><Button variant="ghost" size="sm" aria-label={label} onClick={() => { setDraft(current); setOpen(true) }}><Pencil className="mr-1 h-3.5 w-3.5"/>Edit</Button>{fields.some(([field]) => Boolean(findEdit(field))) && <Badge variant="info">edited</Badge>}</div>; return <div className="mt-3 grid gap-2" onKeyDown={(event) => { if (event.key === 'Escape') setOpen(false); if (event.key === 'Enter') { event.preventDefault(); save() } }}>{fields.map(([field, value]) => { const original = findEdit(field)?.original ?? value; return <label key={field} className="text-xs font-medium capitalize">{field.replace(/([A-Z])/g, ' $1')}<Input value={draft[field] ?? ''} onChange={(event) => setDraft({ ...draft, [field]: event.target.value })}/>{draft[field] !== original && <span className="text-text-muted">Original: <span className="line-through">{original || '(blank)'}</span></span>}</label> })}<div className="flex gap-2"><Button size="sm" onClick={save}>Save</Button><Button size="sm" variant="outline" onClick={() => setOpen(false)}>Cancel</Button></div></div> }
const RESOLUTION_LABELS: Record<ImportDiagnostic['resolution'], string> = { EDIT_FIELD: 'Edit the highlighted field', MAP_COLUMNS: 'Map columns', REPLACE_FILE: 'Replace file', DOWNLOAD_TEMPLATE: 'Use the RevME template', REMOVE_ROW: 'Remove this row', CONTACT_ADMIN: 'Contact an administrator', RETRY: 'Retry validation', NONE: 'Review this issue' }
function ImportDiagnosticIssue({ diagnostic }: { diagnostic: ImportDiagnostic }) { const isError = diagnostic.severity === 'ERROR'; return <div className={`flex gap-2 text-sm ${isError ? 'text-error' : 'text-warning'}`}><AlertCircle className="mt-0.5 h-4 w-4 shrink-0"/><div><p className="font-medium">{diagnostic.title}</p>{diagnostic.provenance && <p className="font-mono text-xs">{diagnostic.provenance}</p>}<p className="text-foreground">{diagnostic.explanation}</p><p className="mt-1 text-xs font-medium">{RESOLUTION_LABELS[diagnostic.resolution]}</p></div></div> }
function History({ history, loading, onChanged }: { history: Batch[]; loading: boolean; onChanged: () => Promise<void> }) {
  const [withdrawTeam, setWithdrawTeam] = useState<BatchTeam | null>(null)
  const [withdrawing, setWithdrawing] = useState(false)
  const withdraw = async () => { if (!withdrawTeam) return; setWithdrawing(true); try { await withdrawSupervisorImportedTeam(withdrawTeam.id); toast.success('Team withdrawn from approval'); setWithdrawTeam(null); await onChanged() } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not withdraw team') } finally { setWithdrawing(false) } }
  const row = (batch: Batch) => ({ count: batch.teams.length || batch.summaryJson.result?.summary.teamsCreated || batch.summaryJson.preview?.summary?.totalRows || 0, date: new Date(batch.createdAt).toISOString().slice(0, 10) })
  const teams = (batch: Batch) => batch.teams.length ? <div className="mt-3 space-y-2">{batch.teams.map((team) => <div key={team.id} className="flex flex-wrap items-center justify-between gap-2 rounded-md border border-border bg-surface p-2"><div><p className="font-medium">{team.name}</p><p className="font-mono text-xs text-text-secondary">{team.externalTeamId}</p></div><div className="flex items-center gap-2"><Badge variant={team.status === 'PENDING_APPROVAL' ? 'warning' : team.status === 'REJECTED' ? 'neutral' : 'success'}>{team.status === 'REJECTED' ? 'withdrawn' : team.status.toLowerCase().replace('_', ' ')}</Badge>{team.status === 'PENDING_APPROVAL' && <Button size="sm" variant="outline" className="text-error" onClick={() => setWithdrawTeam(team)}><Trash2 className="mr-1 h-3.5 w-3.5"/>Withdraw</Button>}</div></div>)}</div> : null
  return <><Card><CardHeader><CardTitle className="font-display">Import history</CardTitle><CardDescription>Your 25 most recent roster batches</CardDescription></CardHeader><CardContent>{loading ? <Loader2 className="h-5 w-5 animate-spin text-primary"/> : history.length ? <><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead><tr className="border-b border-border text-text-secondary"><th className="p-3">Import</th><th className="p-3">Season</th><th className="p-3 text-right">Teams</th><th className="p-3">Status</th><th className="p-3 text-right">Uploaded</th></tr></thead><tbody>{history.map((batch) => <tr key={batch.id} className="border-b border-border align-top"><td className="p-3"><details><summary className="cursor-pointer font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">{batch.fileName}</summary>{teams(batch)}</details></td><td className="p-3">{batch.season.name}</td><td className="p-3 text-right tabular-nums">{row(batch).count}</td><td className="p-3"><BatchStatus status={batch.status}/></td><td className="p-3 text-right font-mono text-sm tabular-nums">{row(batch).date}</td></tr>)}</tbody></table></div><div className="grid gap-3 md:hidden">{history.map((batch) => <div key={batch.id} className="rounded-lg border border-border bg-surface-secondary p-4"><div className="flex items-start justify-between gap-3"><p className="break-all font-medium">{batch.fileName}</p><BatchStatus status={batch.status}/></div><p className="mt-2 text-sm text-text-secondary">{batch.season.name} · {row(batch).date}</p>{teams(batch)}</div>)}</div></> : <div className="py-8 text-center"><Users className="mx-auto mb-2 h-9 w-9 text-text-muted"/><p>No roster imports yet.</p><Button variant="outline" className="mt-3" onClick={() => void downloadSupervisorRosterTemplate().catch((error) => toast.error(error instanceof Error ? error.message : 'Template download failed'))}><Download className="mr-2 h-4 w-4"/>Start from the template</Button></div>}</CardContent></Card><ConfirmDialog open={Boolean(withdrawTeam)} onOpenChange={(open) => { if (!open) setWithdrawTeam(null) }} title="Withdraw this imported team?" description={`${withdrawTeam?.name ?? 'This team'} will be removed from admin approval. Its audit history will be retained and no student email will be sent.`} confirmLabel="Withdraw team" loading={withdrawing} onConfirm={withdraw}/></>
}
function BatchStatus({ status }: { status: string }) { return <Badge variant={status === 'COMPLETED' ? 'success' : status === 'CONFIRMED' ? 'warning' : 'neutral'}>{status.toLowerCase()}</Badge> }

const MAPPING_FIELDS = ['universityName', 'teamExternalId', 'teamName', 'submitter.firstName', 'submitter.lastName', 'submitter.email', 'member1.firstName', 'member1.lastName', 'member1.email', 'member2.firstName', 'member2.lastName', 'member2.email', 'member3.firstName', 'member3.lastName', 'member3.email', 'member4.firstName', 'member4.lastName', 'member4.email'] as const
function ManualMapping({ rows, loading, onApply }: { rows: string[][]; loading: boolean; onApply: (mapping: TeamImportColumnMapping) => void }) {
  const [headerRowIndex, setHeaderRowIndex] = useState(0); const [fields, setFields] = useState<Record<number, string>>({})
  const headers = rows[headerRowIndex] ?? []; const selected = Object.values(fields).filter(Boolean); const ready = ['universityName', 'teamExternalId', 'submitter.firstName', 'submitter.lastName', 'submitter.email'].every((field) => selected.includes(field)) && selected.length >= 6 && new Set(selected).size === selected.length
  return <div className="rounded-lg border border-border bg-surface-secondary p-4"><h3 className="font-display font-semibold">Map columns manually</h3><p className="mt-1 text-sm text-text-secondary">Choose the header row, then match each source column. RevME will run the full validator after you apply it.</p><label className="mt-3 block text-sm font-medium">Header row<select className="ml-2 rounded-md border border-border bg-surface px-2 py-1" value={headerRowIndex} onChange={(event) => { setHeaderRowIndex(Number(event.target.value)); setFields({}) }}>{rows.map((_, index) => <option key={index} value={index}>Row {index + 1}</option>)}</select></label><div className="mt-3 grid gap-2 sm:grid-cols-2">{headers.map((header, column) => <label key={column} className="text-sm"><span className="block truncate font-mono text-xs text-text-secondary">Column {column + 1}: {header || '(blank)'}</span><select className="mt-1 w-full rounded-md border border-border bg-surface px-2 py-2" value={fields[column] ?? ''} onChange={(event) => setFields({ ...fields, [column]: event.target.value })}><option value="">Ignore this column</option>{MAPPING_FIELDS.map((field) => <option key={field} value={field} disabled={selected.includes(field) && fields[column] !== field}>{field}</option>)}</select></label>)}</div><Button className="mt-4" disabled={!ready || loading} onClick={() => onApply({ headerRowIndex, columnMap: Object.entries(fields).filter(([, field]) => field).map(([column, field]) => ({ column: Number(column), field: field as TeamImportColumnMapping['columnMap'][number]['field'], confidence: 1 })) })}>Apply manual mapping</Button>{!ready && <p className="mt-2 text-xs text-text-secondary">Map university, team ID, corresponding member first name, last name, email, and at least one additional field.</p>}</div>
}
