import { redirect } from 'next/navigation'
import Link from 'next/link'
import { getSession } from '@/lib/auth'
import { getSupervisorCoaching } from '@/server/supervisor-coaching'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { formatMape } from '@/lib/learning-analytics'

export default async function SupervisorDebriefPage({ params }: { params: Promise<{ roundId: string }> }) {
  const user = await getSession(); if (!user || user.role !== 'SUPERVISOR') redirect('/dashboard')
  const { roundId } = await params; const coaching = await getSupervisorCoaching(user.id, roundId)
  if (!coaching?.round || !coaching.round.leaderboardVisible) return <Card><CardContent className="py-16 text-center">This classroom debrief is available after scores are published.</CardContent></Card>
  const scored = coaching.teams.filter((team) => team.score != null)
  const podium = [...scored].sort((a, b) => a.score! - b.score!).slice(0, 3)
  const maxBin = Math.max(1, ...(coaching.insights?.histogram || []).map((bin) => bin.count))
  return <div className="space-y-8 print:bg-white print:text-black"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold uppercase tracking-wider text-accent">{coaching.season.name}</p><h1 className="font-display text-4xl font-semibold">Round {coaching.round.number} classroom debrief</h1><p className="mt-2 text-text-secondary">An anonymized discussion view for projection.</p></div><Link href="/dashboard" className="text-sm text-primary print:hidden">Exit presentation</Link></div>
    <div className="grid gap-4 md:grid-cols-3"><Card><CardContent className="py-6"><p className="text-sm text-text-secondary">Teams scored</p><p className="font-display text-4xl tabular-nums">{scored.length}</p></CardContent></Card><Card><CardContent className="py-6"><p className="text-sm text-text-secondary">Cohort average</p><p className="font-display text-4xl tabular-nums">{formatMape(scored.length ? scored.reduce((sum, team) => sum + team.score!, 0) / scored.length : null)}</p></CardContent></Card><Card><CardContent className="py-6"><p className="text-sm text-text-secondary">Score range</p><p className="font-display text-2xl tabular-nums">{formatMape(scored.length ? Math.min(...scored.map((team) => team.score!)) : null)}–{formatMape(scored.length ? Math.max(...scored.map((team) => team.score!)) : null)}</p></CardContent></Card></div>
    {podium.length > 0 && <Card><CardHeader><CardTitle>Round podium</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-3">{podium.map((team, index) => <div key={team.id} className="rounded-xl border border-border bg-surface-secondary p-5 text-center"><p className="font-display text-4xl">#{index + 1}</p><p className="mt-1 font-semibold">Team {index + 1}</p><p className="font-mono tabular-nums text-primary">{formatMape(team.score)}</p></div>)}</CardContent></Card>}
    {coaching.insights?.common && <Card className="border-accent/30"><CardHeader><CardTitle>Common forecasting pattern</CardTitle></CardHeader><CardContent><p className="text-xl">{coaching.insights.common.teamCount} of {coaching.insights.common.totalTeams} teams {coaching.insights.common.direction.toLowerCase()}-forecast {coaching.insights.common.marketName} {coaching.insights.common.metric === 'ADR' ? 'ADR' : 'occupancy'}.</p><p className="mt-2 text-text-secondary">Discuss which shared assumption may have driven this direction; the data indicates a pattern, not a cause.</p></CardContent></Card>}
    <Card><CardHeader><CardTitle>Anonymized score histogram</CardTitle></CardHeader><CardContent><div className="flex h-56 items-end justify-around gap-4 border-b border-border px-4">{coaching.insights?.histogram.map((bin) => <div key={bin.label} className="flex h-full flex-1 flex-col justify-end text-center"><span className="mb-2 font-mono text-sm tabular-nums">{bin.count}</span><div className="mx-auto w-full max-w-24 rounded-t bg-primary" style={{ height: `${Math.max(3, (bin.count / maxBin) * 80)}%` }} /><span className="mt-2 text-xs text-text-muted">{bin.label}</span></div>)}</div><p className="mt-3 text-xs text-text-muted">Combined round MAPE · lower is better</p></CardContent></Card>
    {coaching.insights?.commonMiss && <Card className="border-warning/30"><CardHeader><CardTitle>Common miss to discuss</CardTitle></CardHeader><CardContent><p className="text-xl">{coaching.insights.commonMiss.marketName} · {coaching.insights.commonMiss.metric === 'ADR' ? 'ADR' : 'Occupancy'} averaged {formatMape(coaching.insights.commonMiss.averageError)} error.</p><p className="mt-2 text-text-secondary">Ask which shared baseline or market assumption deserves rechecking.</p></CardContent></Card>}
    {(coaching.insights?.marketUpdates.length ?? 0) > 0 && <Card><CardHeader><CardTitle>Market explanation</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2">{coaching.insights?.marketUpdates.map((update) => <div key={update.marketName} className="rounded-xl bg-surface-secondary p-4"><p className="font-semibold">{update.marketName}: {update.headline}</p><p className="mt-1 text-sm text-text-secondary">{update.whatChanged}</p></div>)}</CardContent></Card>}
  </div>
}
