import type { TeamImportColumnLabel, TeamImportOverrideField } from './types'

export const IMPORT_DIAGNOSTIC_CODES = [
  'FILE_REQUIRED', 'FILE_EMPTY', 'FILE_TOO_LARGE', 'FILE_UNSUPPORTED', 'FILE_TEMPORARY',
  'FILE_CONTENT_MISMATCH', 'CSV_BINARY', 'CSV_ENCODING_UNSUPPORTED', 'WORKBOOK_UNREADABLE',
  'WORKBOOK_UNSAFE', 'LAYOUT_UNRECOGNIZED', 'LAYOUT_REQUIRED_COLUMNS_MISSING',
  'METADATA_TEAM_COUNT_MISMATCH', 'METADATA_INSTRUCTOR_MISMATCH', 'METADATA_CONTEXT_MISMATCH', 'UNIVERSITY_REQUIRED',
  'UNIVERSITY_UNKNOWN', 'UNIVERSITY_MISMATCH', 'TEAM_ID_REQUIRED', 'TEAM_ID_DUPLICATE_FILE',
  'TEAM_ID_DUPLICATE_SEASON', 'TEAM_NAME_REQUIRED', 'TEAM_NAME_DUPLICATE_FILE',
  'TEAM_NAME_DUPLICATE_SEASON', 'PERSON_EMAIL_REQUIRED', 'PERSON_EMAIL_MALFORMED',
  'PERSON_GLUED_NAME', 'PERSON_NAME_MISMATCH', 'PERSON_DUPLICATE_TEAM',
  'PERSON_DUPLICATE_FILE', 'PERSON_ROLE_INVALID', 'PERSON_UNIVERSITY_MISMATCH',
  'MEMBERSHIP_CONFLICT', 'TEAM_MEMBER_MINIMUM', 'TEAM_MEMBER_MAXIMUM',
  'SUPERVISOR_REQUIRED', 'SUPERVISOR_NOT_FOUND', 'SUPERVISOR_ROLE_INVALID',
  'SUPERVISOR_UNIVERSITY_MISMATCH', 'SUPERVISOR_AMBIGUOUS', 'CAPACITY_REACHED',
  'SEASON_UNAVAILABLE', 'SEASON_REGISTRATION_CLOSED', 'STALE_FILE_HASH',
  'AUTH_FORBIDDEN', 'UNKNOWN_IMPORT_ERROR',
] as const

export type ImportDiagnosticCode = typeof IMPORT_DIAGNOSTIC_CODES[number]
export type ImportScope = 'FILE' | 'WORKBOOK' | 'LAYOUT' | 'METADATA' | 'TEAM' | 'PERSON' | 'ACCOUNT' | 'MEMBERSHIP' | 'UNIVERSITY' | 'SEASON' | 'CAPACITY' | 'DUPLICATE' | 'STALE_HASH' | 'AUTH'
export type ImportResolutionAction = 'EDIT_FIELD' | 'MAP_COLUMNS' | 'REPLACE_FILE' | 'DOWNLOAD_TEMPLATE' | 'REMOVE_ROW' | 'CONTACT_ADMIN' | 'RETRY' | 'NONE'
export type ImportAiPolicy = 'NEVER' | 'EXPLAIN_ONLY' | 'SUGGEST_EDIT'
export interface ImportDiagnosticTarget { rowNumber?: number; columnLabel?: TeamImportColumnLabel; field?: TeamImportOverrideField | 'universityName' }
export interface ImportDiagnostic { code: ImportDiagnosticCode; severity: 'ERROR' | 'WARNING'; scope: ImportScope; target?: ImportDiagnosticTarget; provenance?: string; title: string; explanation: string; resolution: ImportResolutionAction; editable: boolean; aiPolicy: ImportAiPolicy; legacyMessage: string }
