import { deflateRawSync } from 'zlib'
import { TEAM_IMPORT_EXAMPLE_MARKER, TEAM_IMPORT_PERSON_LABELS } from './overrides'

export const ROSTER_MEMBER_GROUPS = TEAM_IMPORT_PERSON_LABELS
export const ROSTER_PERSON_HEADERS = ['First Name', 'Last Name', 'Email'] as const
export const ROSTER_TEAM_HEADERS = ['Institution', 'TeamID', "Team's selected name (optional)"] as const

function esc(value: string) { return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;') }
function col(index: number) { let n = index + 1; let out = ''; while (n) { out = String.fromCharCode(65 + ((n - 1) % 26)) + out; n = Math.floor((n - 1) / 26) } return out }
function crc32(buffer: Buffer) { let crc = 0xffffffff; for (const byte of buffer) { crc ^= byte; for (let bit = 0; bit < 8; bit += 1) crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0) } return (crc ^ 0xffffffff) >>> 0 }
function zip(entries: Array<{ name: string; content: string }>) { const local: Buffer[] = []; const central: Buffer[] = []; let offset = 0; for (const entry of entries) { const name = Buffer.from(entry.name); const source = Buffer.from(entry.content); const compressed = deflateRawSync(source); const checksum = crc32(source); const h = Buffer.alloc(30); h.writeUInt32LE(0x04034b50, 0); h.writeUInt16LE(20, 4); h.writeUInt16LE(8, 8); h.writeUInt32LE(checksum, 14); h.writeUInt32LE(compressed.length, 18); h.writeUInt32LE(source.length, 22); h.writeUInt16LE(name.length, 26); local.push(h, name, compressed); const d = Buffer.alloc(46); d.writeUInt32LE(0x02014b50, 0); d.writeUInt16LE(20, 4); d.writeUInt16LE(20, 6); d.writeUInt16LE(8, 10); d.writeUInt32LE(checksum, 16); d.writeUInt32LE(compressed.length, 20); d.writeUInt32LE(source.length, 24); d.writeUInt16LE(name.length, 28); d.writeUInt32LE(offset, 42); central.push(d, name); offset += h.length + name.length + compressed.length } const cd = Buffer.concat(central); const end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50, 0); end.writeUInt16LE(entries.length, 8); end.writeUInt16LE(entries.length, 10); end.writeUInt32LE(cd.length, 12); end.writeUInt32LE(offset, 16); return Buffer.concat([...local, cd, end]) }
function cell(column: number, row: number, value: string, style = 0) { return value ? `<c r="${col(column)}${row}" t="inlineStr" s="${style}"><is><t>${esc(value)}</t></is></c>` : `<c r="${col(column)}${row}" s="${style}"/>` }
function worksheet(rows: string[][], styles: (row: number, column: number) => number, extras = '') { const body = rows.map((values, ri) => `<row r="${ri + 1}">${values.map((value, ci) => cell(ci, ri + 1, value, styles(ri, ci))).join('')}</row>`).join(''); return `<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheetViews><sheetView workbookViewId="0"><pane ySplit="8" topLeftCell="A9" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols><col min="2" max="4" width="28" customWidth="1"/><col min="5" max="19" width="20" customWidth="1"/></cols><sheetData>${body}</sheetData>${extras}</worksheet>` }

export function buildRosterTemplate(args: { universityName: string; instructorName: string; instructorEmail: string }) {
  const instructions = [['RevME Forecaster Cup — Team Roster'], [''], ['• Enter one team per row.'], ['• The first person triplet is the student who submits forecasts.'], ['• Use real university email addresses; accounts are created or matched by email.'], ['• A supervisor may register no more than 10 teams.'], ["• Don't move or rename the headers."], ['• Delete the grey example row before submitting.']]
  const section = ['', ...ROSTER_TEAM_HEADERS, ...ROSTER_MEMBER_GROUPS.flatMap((group) => [group, '', ''])]
  const headers = ['', '', '', '', ...ROSTER_MEMBER_GROUPS.flatMap(() => ROSTER_PERSON_HEADERS)]
  const example = ['', args.universityName, TEAM_IMPORT_EXAMPLE_MARKER, 'Example Revenue Team', 'Alex', 'Student', 'alex@example.edu']
  const entries = Array.from({ length: 10 }, (_, index) => ['', args.universityName, `${args.universityName}${index + 1}`, '', ...Array(15).fill('')])
  const registration = [[], ['', 'Your University', args.universityName], ['', "Instructor's Name", args.instructorName], ['', "Instructor's Email", args.instructorEmail], ['', 'Number of teams (no more than 10)', ''], [], section, headers, example, ...entries]
  const emailColumns = [6, 9, 12, 15, 18]
  const comments = `<?xml version="1.0" encoding="UTF-8"?><comments xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><authors><author>RevME</author></authors><commentList>${emailColumns.map((column) => `<comment ref="${col(column)}8" authorId="0"><text><t>Use the student's university email</t></text></comment>`).join('')}</commentList></comments>`
  const contentTypes = `<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="vml" ContentType="application/vnd.openxmlformats-officedocument.vmlDrawing"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/xl/comments1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.comments+xml"/></Types>`
  const styles = `<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Aptos"/></font><font><b/><sz val="11"/><name val="Aptos"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FFE5E7EB"/></patternFill></fill></fills><borders count="2"><border/><border><left style="thin"/><right style="thin"/><top style="thin"/><bottom style="thin"/></border></borders><cellXfs count="4"><xf fontId="0" fillId="0" borderId="0"/><xf fontId="1" fillId="0" borderId="1" applyFont="1" applyBorder="1"/><xf fontId="0" fillId="0" borderId="1" applyBorder="1"/><xf fontId="0" fillId="2" borderId="1" applyFill="1" applyBorder="1"/></cellXfs></styleSheet>`
  return zip([
    { name: '[Content_Types].xml', content: contentTypes },
    { name: '_rels/.rels', content: `<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>` },
    { name: 'xl/workbook.xml', content: `<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Instructions" sheetId="1" r:id="rId1"/><sheet name="Registration Form" sheetId="2" r:id="rId2"/></sheets></workbook>` },
    { name: 'xl/_rels/workbook.xml.rels', content: `<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>` },
    { name: 'xl/styles.xml', content: styles },
    { name: 'xl/worksheets/sheet1.xml', content: worksheet(instructions, (row) => row === 0 ? 1 : 0) },
    { name: 'xl/worksheets/sheet2.xml', content: worksheet(registration, (row) => row === 6 || row === 7 ? 1 : row === 8 ? 3 : row >= 9 ? 2 : 0, '<legacyDrawing r:id="rId2"/>') },
    { name: 'xl/worksheets/_rels/sheet2.xml.rels', content: `<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments" Target="../comments1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/vmlDrawing" Target="../drawings/vmlDrawing1.vml"/></Relationships>` },
    { name: 'xl/comments1.xml', content: comments },
    { name: 'xl/drawings/vmlDrawing1.vml', content: `<?xml version="1.0"?><xml xmlns:v="urn:schemas-microsoft-com:vml" xmlns:x="urn:schemas-microsoft-com:office:excel"><x:ClientData ObjectType="Note"/></xml>` },
  ])
}
